services:
  app:
    image: ardfordev/maven-app:${IMAGE_TAG}
    container_name: maven-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - app_logs:/var/log

volumes:
  app_logs:

networks:
  app-network:
    driver: bridge